### PR TITLE
Feat/add interactive shell

### PR DESCRIPTION
**Pull request by shtayeb**
Execute python code in your Django app context.

### CODE REVIEW

**Comment by anze3db** [comment]
I played around with it, and I like it. I agree it's much more convenient than using `python manage.py shell`. Let's figure out how to include it!

I'm not a fan of the selector as the first screen, but I think a key action (ctrl+i is already used by trogon, but I think ctrl+j works well) to switch to the interactive shell screen and back works well.

We could also add a command line argument as a shortcut to go directly into the interactive shell, something like:

```python
python manage.py tui shell # to open up the new interactive shell directly
```

What do you think?

**Comment by shtayeb** [comment]
> I played around with it, and I like it. I agree it's much more convenient than using `python manage.py shell`. Let's figure out how to include it!
> 
> I'm not a fan of the selector as the first screen, but I think a key action (ctrl+i is already used by trogon, but I think ctrl+j works well) to switch to the interactive shell screen and back works well.
> 
> We could also add a command line argument as a shortcut to go directly into the interactive shell, something like:
> 
> ```python
> python manage.py tui shell # to open up the new interactive shell directly
> ```
> 
> What do you think?

I agree 100%

**Comment by shtayeb** [comment]
@anze3db, I added your suggestions.

You can now open shell directly with `python manage.py tui --shell` and switch to commands and shell with `ctrl+j`.

**Comment by anze3db** [comment]
Looks good. I will merge and then do some cleanup/improvements and a new release. Thanks for the contribution, it looks awesome! 👍

**Pull request merged**
